phase3/README.md

Added some AWS certs and resources for the same

added AWS certifications

---

phase2/README.md
phase3/README.md
phase4/README.md

Wooooo, this is awesome @rishabkumar7 + @madebygps !!
I really like the timeline behind it, makes it very explicit and clear for a beginner. 
And I like how each phase has the same / similar structure in the docs, makes it easy to follow.
Just a start, I'll come back and iteratively add to it over time...

feat: some general additions

---

phase3/README.md

Add missing // so it links to your blog instead of 404

Fix absolute link to your blog

---

README.md

Used the custom domain as the link instead of the github-pages link

updated the link to web version of guide

---

Contributors.md

added the markdown file for contributors

---

.github/PULL_REQUEST_TEMPLATE/bugs-only.md
.github/PULL_REQUEST_TEMPLATE/submit-project.md

Added pull request templates:
- Project Submission
- Bugs

Add PULL REQUEST templates

---

phase4/README.md

I believe these tutorials will assist others in their DevOps development.
Added
- DevOps Journey Using Azure DevOps
- DevOps the Hardway - Azure
- DevOps the Hardway - AWS

Added some additional tutorials

---

index.html

Add a dark/light mode toggle in the guide portion of the page.

Add support for dark theme

---

phase3/README.md
projects/README.md

Added my website 'Cloud is free', in which I made and documented three projects to do after validating a Cloud certification. This is my way of helping others.
I let you make your own opinion on the website: https://cloudisfree.com
Thank you.

Add Project website 'Cloud Is Free'

---

phase3/README.md

Minor typo fix

---

.gitignore
CODEOWNERS
_navbar.md
pt/CODE_OF_CONDUCT.md
pt/CONTRIBUTING.md
pt/README.md
pt/_coverpage.md
pt/_navbar.md
pt/_sidebar.md
pt/phase0/README.md

I'll be sending the PR's based on the paths.

Fix #28 - Root path

---

.gitignore
CODEOWNERS
_navbar.md
pt/CODE_OF_CONDUCT.md
pt/CONTRIBUTING.md
pt/README.md
pt/_coverpage.md
pt/_navbar.md
pt/_sidebar.md
pt/more-topics/FAQ.md
pt/more-topics/README.md
pt/phase0/README.md
pt/phase1/README.md

his PR has the[ #36](https://github.com/learntocloud/learn-to-cloud/pull/36) as dependency.

Fix #28 - Phase1 Path Pt

---

phase1/README.md

Added a link to the Phase1 Readme to a video series which teaches Networking. It's a little less daunting, and more approachable than the FreeCodeCamp 9 hour college course.

Additional Resource for Learning Networking

---

phase0/README.md

I fixed the playlist misspelling in the Phase 0 page per issue #48.

Fixed playlist word misspelling.

---

phase1/README.md
phase3/README.md

Adding a link for the Linux Hackathon

Adding Linux Hackathon

---

projects/README.md

Found out that Amazon offers free workshops people can leverage to up-skill!

Updated Projects README.md

---

fr/README.md
fr/_sidebar.md
fr/phase1/README.md
fr/phase2/README.md
fr/phase3/README.md
fr/phase4/README.md

I corrected some minor grammar errors and punctuation.
I also added the "(Anglais)" tag for certain links to indicate that they are only available in English. It seems like a better user experience for anyone who is not comfortable with English, so they don't click on links they won't understand. I did not check every link, I assumed links from big corporation documentation had translations.

Minor corrections of the french version

---

fr/phase0/README.md

I have translated [README.md](https://github.com/learntocloud/learn-to-cloud/blob/main/fr/phase0/README.md) to French
Resolves #35

Translated to French

---

pt/phase2/README.md

I am continuing the translation into Portuguese that I saw in [this issue](https://github.com/learntocloud/learn-to-cloud/issues/28)

Phase2 translated to portuguese

---

pt/phase2/README.md
pt/phase3/README.md

Continuing on the mission of translating into portuguese in relation [this issue](https://github.com/learntocloud/learn-to-cloud/issues/28)

Phase 3 translated to brazilian portuguese

---

pt/phase3/README.md
pt/phase4/README.md

One more phase translated into portuguese. Task relationed [this issue](https://github.com/learntocloud/learn-to-cloud/issues/28)

Phase 4 translated to brazilian portuguese

---

pt/_navbar.md
pt/_sidebar.md
pt/phase0/README.md
pt/phase1/README.md
pt/phase2/README.md
pt/phase3/README.md
pt/phase4/README.md

Hi,
I've update the navbar file and some links around pt translation.

Small adjustments in pt translation

---

docusaurus.config.js

Just a fix pointing to the right GitHub org.

Fixed GitHub link

---

docusaurus.config.js

Added GPS's study plan to navbar

---

docusaurus.config.js
package-lock.json
package.json

Added Google Analytics to the docusaurus site

Feature: add google analytics

---

docusaurus.config.js

added discord link to the navbar and moved LTC roadmap to the left of navbar

Added Discord link

---

docusaurus.config.js

This allows users who visit the website to edit a page through GitHub by opening a PR.

Updated the URL for Edit this page functionality

---

docs/phase1/README.md
docs/phase3/README.md
docs/phase4/README.md

added some video embeds to phases.

Added embeds to phases

---

docs/projects/README.md

Added resources

---

docs/phase1/README.md

Added bfb series'

---

docs/phase2/README.md
docs/phase3/README.md

Updated "these three topics" to "these two topics" as there are two topics listed in the tables below . 
A minor Update for the "how to break down this section" portion of Phase 2 and phase 3.

Minor fix to phase 2 and 3 doc

---

docs/phase1/README.md
docs/phase3/README.md

I corrected a few typos in the phase1 doc and made slight grammar changes to the Cloud Resume Challenge table in the phase3 doc to standardize the punctuation.

Fixed spelling and grammar.

---

docs/phase5/README.md

Added a popular cloud security resource used in the community: https://cloud.hacktricks.xyz

Added Hacktricks Cloud

---

src/components/HomepageApi/styles.module.css

fix theme color switch position

remove button margin top to align the theme toggle icon in the navbar

---

docs/phase4/README.md

Added the Capstone Project for Phase 4: QR Code Generator

Added phase 4 capstone project

---

docusaurus.config.js
i18n/pt/docusaurus-plugin-content-docs/current/_navbar.md

updated the discord link and invite in nav bar

updated discord link

---

docusaurus.config.js

Added Footer with relevant links and decreased the amount of links in Navbar.

UI changes - Added footer and updated Navigation bar.

---

docusaurus.config.js
src/pages/contributors.md

Checked `docusaurus.config.js` and the `contributors.md`

Contributors page fix

---

docs/phase2/README.md

Changed URL to playlist instead of the first video

Updated Python for Beginners URL

---

docs/phase1/5-ctf.md

added note discouraging solution sharing and link to answer key

added note to ctf

---

docusaurus.config.js
package-lock.json
package.json
yarn.lock

This PR updates the dependencies for both `npm` and `yarn` lock files.

Fix dependencies warnings

---

docs/phase5/10-capstone.md
docs/phase5/README.md
docs/phase5/csf-projects.md

Added Capstone to flow better with the overall pattern of the other phases of LTC
Additional projects have been added to the csf-projects.md for those looking for other project ideas

Added Capstone to CSF Phase 5 and Additional Projects to close #243

---

docs/phase0/README.md

Fixed link to GitHub repository on the first line item for Prerequisits.

Corrected Phase0 README.md link to GitHub
